### ISSUE TITLE
Move this repo to a RH owned user/org

### ISSUE THREAD

**Issue by akofink** [OpenSCAP/openscap_parser#14]
Foreman and the insights group uses this gem. I'd be fine to put it in either org.

**Comment by akofink** [comment]
@dLobatog @bastilian any suggestions here? I think it's either RedHatInsights or theforeman GitHub org, or we could make it openscap_parser/openscap_parser.

**Comment by dLobatog** [comment]
@akofink https://github.com/openscap said they'd be OK with it but still haven't received any answer - I'll ping them again

**Comment by akofink** [comment]
:100: even better :)

**Comment by dLobatog** [comment]
Closing :smile:
